/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface PluginImportItem {
  source: string
  transformEs: string
  transformStyle?: string
  ignoreComponents?: Array<string>
  snakeCase: boolean
}
export interface PackageConfig {
  transform: string
  preventFullImport: boolean
  skipDefaultConversion: boolean
}
/**
 * Internal any plugin
*/
export interface Extensions {
  modularizeImports?: Record<string, PackageConfig>
  pluginImport?: Array<PluginImportItem>
}
export interface TransformConfigNapi {
  /** Raw swc options */
  swc: import('./types').SwcOptions
  /** Internal rust-swc Plugins */
  extensions: Extensions
}
export function minify(config: string, code: string, filename: string, map?: string | undefined | null): Promise<{ code: string, map?: string }>
export interface Output {
  code: string
  map?: string
}
export function transform(config: TransformConfigNapi, code: string): Output
