/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function minify(config: string, code: string, filename: string, map?: string | undefined | null): Promise<{ code: string, map?: string }>
export function transform(config: string, code: string): Promise<{ code: string, map?: string }>
