# We use different scopes is because that swc_core has 2 mutual features
# that plugin-rt and plugin-mode cannot enable at the same time
# If we make plugins and core at the same workspace, cargo check --workspace will fail

cargo-features = ["strip"]

[workspace]
members = ["plugin-import", "react-const-elements"]
resolver = "2"

[profile.release]
strip = "symbols"

# Enable following optimization on CI, based on env variable
# lto = true
# codegen-units = 1

[workspace.dependencies]
rustc-hash = { version = "1.1.0" }
anyhow = { version = "1.0.69" }
dashmap = { version = "5.4.0" }
serde = "1.0.163"
serde_json = "1.0.91"
swc_core = { version = "0.82.7", default-features = false }
